POST http://localhost:5000/api/messages/classify
Content-Type: application/json

{
  "Text": "Dün sabah kargom kargoya verilmişti. nerede kaldı?",
  "UserId": "httptest"
}

### Get Message
GET http://localhost:5000/api/messages?RoutingKey=support.cargo.management
Accept: application/json