POST http://localhost:5000/api/messages/classify
Content-Type: application/json

{
  "Text": "Dün sabah kargom kargoya verilmişti. nerede kaldı?",
  "UserId": "httptest"
}

### Get Message
GET http://localhost:5000/api/tickets/support?RoutingKey=support.cargo.tracking
Accept: application/json

### 
GET http://localhost:5000/api/tickets/conversation?TicketId=86009d11-7d4b-45fb-bad6-8a01dd6e9d69
Accept: application/json

### Get Ticket
GET http://localhost:5000/api/tickets?TicketId=86009d11-7d4b-45fb-bad6-8a01dd6e9d69